Improvement/add real docs
ditrit/badaas pull request #21
Opened 2022-10-18 13:24 UTC by slashformotion

improve the documentation

2022-12-05 10:03 UTC, Zorin95670 requested changes

2022-12-05 10:03 UTC, Zorin95670 commented on README.md
> +(WIP)
nope, please complete

2022-12-05 10:03 UTC, Zorin95670 commented on README.md
> +### Configuration
add section for each themes of configuration, list and explain all commands

2022-12-05 10:03 UTC, Zorin95670 commented on README.md
> +(WIP)
complete or remove

2022-12-05 10:03 UTC, Zorin95670 commented on README.md
> +## Directory structure
move in contributing

2022-12-05 10:03 UTC, Zorin95670 commented on README.md
> +## E2E testing
move in contributing

2022-12-05 13:08 UTC, slashformotion commented on README.md
> +(WIP)
ben on a pas d'image docker officielle donc avec xavier on s'était dit qu'on compléterai plus tard.

2022-12-05 15:49 UTC, slashformotion commented on README.md
> +(WIP)
docker build -t imgname .

2022-12-06 09:36 UTC, Zorin95670 requested changes

2022-12-06 09:36 UTC, Zorin95670 commented on badaas.yml.example
> +    # Number of time badaas will try to establish a connection to the database.
missing default

2022-12-06 09:36 UTC, Zorin95670 commented on badaas.yml.example
> +    # Waiting time between connection, in seconds.
missing default

2022-12-06 09:36 UTC, Zorin95670 commented on badaas.yml.example
> -# The settings for the database.
keep explanation of section

2022-12-06 09:36 UTC, Zorin95670 commented on badaas.yml.example
> +server:
add section explanation

2022-12-06 09:36 UTC, Zorin95670 commented on badaas.yml.example
> +  # The maximum timout for read/write ops.
ops?

2022-12-06 09:36 UTC, Zorin95670 commented on badaas.yml.example
> +  pagination:
missing section explanation

2022-12-06 09:36 UTC, Zorin95670 commented on badaas.yml.example
>  logger:
missing section explanation

2022-12-06 09:36 UTC, Zorin95670 commented on badaas.yml.example
> +  # Either dev or prod
for all options value please use `this`

2022-12-06 09:36 UTC, Zorin95670 commented on README.md
> +You can either use the [Docker Install (WIP)](<!-- TODO: link the docker install instructions here and remove the WIP mention-->) or build it from source .
remove wip

2022-12-06 09:36 UTC, Zorin95670 commented on README.md
> +Get the sources of the project, either by visiting the [releases]() page and downloading an archive or clone the main branch (please be aware that is it not a stable version).
rewrite this and put TODO to explain that we have to set release link note here

2022-12-06 09:36 UTC, Zorin95670 commented on README.md
> +```txt
txt -> bash

2022-12-06 09:36 UTC, Zorin95670 commented on README.md
> +***For a full overview of the configuration keys: please head to  [configuration.md](./configuration.md).***
[configuration documentation](./configuration.md)

2022-12-06 09:36 UTC, Zorin95670 commented on README.md
> +See [CONTRIBUTING.md](./CONTRIBUTING.md).
See this section

2022-12-06 09:36 UTC, Zorin95670 commented on CONTRIBUTING.md
> +<h1> Contribute to the development of badaas</h1>
remove h1 and use #

2022-12-06 09:36 UTC, Zorin95670 commented on CONTRIBUTING.md
> +<h1> Contribute to the development of badaas</h1>
Modify all next section by adding a #
`# Tests -> ## Tests`

2022-12-06 09:36 UTC, Zorin95670 commented on configuration.md
> +To see a simple example of a working config file: head to [`badaas.yml.example`](../badaas.yml.example)
simple -> complete

2022-12-09 10:41 UTC, Zorin95670 requested changes

2022-12-09 10:41 UTC, Zorin95670 commented on README.md
> +You can either use the [Docker Install (WIP)](<!-- TODO: link the docker install instructions here and remove the WIP mention-->) or build it from source .
not remove

2022-12-09 10:41 UTC, Zorin95670 commented on badaas.yml.example
> -server:
Rename this file to `badaas.example.yml` to keep syntax highlighting and improve readability.

2022-12-09 15:16 UTC, k-y0u requested changes

2022-12-09 15:16 UTC, k-y0u commented on configuration.md
> +    # Defaults to 5
default

2022-12-09 15:16 UTC, k-y0u commented on configuration.md
> +Badaas offer the possibility to change the log message of the Middleware Logger but provides a sane default. It is formated using the Jinja syntax. The values available are `method`, `url` and `proto
offers

2022-12-09 15:16 UTC, k-y0u commented on configuration.md
> +  # Defaults to `prod`
default

2022-12-09 15:16 UTC, k-y0u commented on configuration.md
> +    # Change the log emitted when badaas receive a request on a valid endpoint.
receives

2022-12-09 15:16 UTC, k-y0u commented on configuration.md
> +  # Defaults to "0.0.0.0"
Default

2022-12-09 15:16 UTC, k-y0u commented on configuration.md
> +  # Defaults to 8000
default

2022-12-09 15:16 UTC, k-y0u commented on configuration.md
> +  # Defaults to 15
default

2022-12-09 15:16 UTC, k-y0u commented on configuration.md
> +  timeout: 15 # in seconds
choose the good place for the unit

2022-12-09 15:16 UTC, k-y0u commented on configuration.md
> +      # Defaults to 100
default

2022-12-09 15:24 UTC, slashformotion commented on badaas.yml.example
> +  # The settings for the initialization of the database
d

2022-12-09 15:32 UTC, slashformotion commented on README.md
> +To quickly get up and running, please head to the [miniblog tutorial](<!-- TODO: link the miniblog tutorial here -->)
Isn't "get up and running" a valid expression ? https://www.linguee.fr/anglais-francais/traduction/up+and+running.html

2022-12-12 13:45 UTC, k-y0u commented on CONTRIBUTING.md
> +- `ressources/` *(Go code)*: Contains the ressources shared with the rest of the codebase (ex: API version).
`ressources/`->`resources/`

2022-12-12 13:45 UTC, k-y0u commented on README.md
> +- **Habilitation**: On a ressource access, Badaas will check if the user is authorized using a RBAC model.
ressource -> resource

2022-12-12 13:45 UTC, k-y0u commented on CONTRIBUTING.md
> +- `ressources/` *(Go code)*: Contains the ressources shared with the rest of the codebase (ex: API version).
Contains the ressources -> Contains the resources

2022-12-12 13:45 UTC, k-y0u commented on README.md
> +- **Querying Resources**: Ressources are accessible via a REST API.
Ressources -> Resources

2022-12-12 13:45 UTC, k-y0u commented on README.md
> +To quickly get up and running, please head to the [miniblog tutorial](<!-- TODO: link the miniblog tutorial here -->)
So it should be `get it/badass/theproject up and running`.

2022-12-12 13:47 UTC, k-y0u commented on README.md
> +CLI flags takes priority on the environment variables and the environment variables take priority on the content of the configuration file.
only one ?

2022-12-12 13:55 UTC, k-y0u requested changes

2022-12-12 13:55 UTC, k-y0u commented on configuration.md
> +> CLI flags take priority on the environment variables and the environment variables take priority on the content of the configuration files.
`configuration files` -> several ?

2022-12-13 08:52 UTC, k-y0u approved these changes

2022-12-13 13:06 UTC, Zorin95670 approved these changes

2022-12-13 13:29 UTC, k-y0u approved these changes

2022-12-13 13:31 UTC, merged