Feature/starting basicauth
ditrit/badaas pull request #22
Opened 2022-10-24 14:15 UTC by slashformotion

2022-11-10 13:25 UTC, Zorin95670 requested changes

2022-11-10 13:25 UTC, Zorin95670 commented on commands/initDatabaseCommands.go
> +	databaseRetryKey := "database.retry"
database.init.retry

2022-11-10 13:25 UTC, Zorin95670 commented on commands/initDatabaseCommands.go
> +	databaseRetryDurationKey := "database.retryDuration"
database.init.retryTime

2022-11-10 13:25 UTC, Zorin95670 commented on services/sessionservice/session.go
> +	sessionDuration = 1 * time.Minute
put this in conf

2022-11-10 13:25 UTC, Zorin95670 commented on services/sessionservice/session.go
> +	pullTime = time.Second * 30
put this in conf

2022-11-10 13:25 UTC, Zorin95670 commented on services/sessionservice/session.go
> +func isExpired(session *models.Session) bool {
to put in models.Session

2022-11-24 16:03 UTC, slashformotion commented on commands/initDatabaseCommands.go
> +	databaseRetryDurationKey := "database.retryDuration"
done in the other PR

2022-11-24 16:03 UTC, slashformotion commented on commands/initDatabaseCommands.go
> +	databaseRetryKey := "database.retry"
done in the other PR

2022-12-05 09:50 UTC, Zorin95670 requested changes
rework on your commit

2022-12-05 09:50 UTC, Zorin95670 commented on persistence/repository/CRUDRepository.go
> +	FindPaginated(squirrel.Sqlizer, pagination.Paginator, ...pagination.SortOption) (*pagination.Page[T], httperrors.HTTPError)
remove and do only one find

2022-12-05 09:50 UTC, Zorin95670 commented on persistence/repository/CRUDRepositoryImpl.go
> +func (repository *CRUDRepositoryImpl[T, ID]) Transaction(transactionFunction func(repo CRUDRepository[T, ID]) (any, error)) (any, httperrors.HTTPError) {
repo ?

2022-12-19 09:06 UTC, Zorin95670 commented on persistence/repository/CRUDRepository.go
> -	Count(squirrel.Sqlizer) (uint, httperrors.HTTPError)
Why do you delete it ?

2022-12-19 10:32 UTC, Zorin95670 requested changes

2022-12-19 10:32 UTC, Zorin95670 commented on services/sessionservice/session.go
> +	fmt.Println(dur)
dur ? println ? :eyes:

2022-12-19 10:32 UTC, Zorin95670 commented on services/sessionservice/session.go
> +	sess := newSession(user.ID, dur)
sess :eyes:

2022-12-19 10:32 UTC, Zorin95670 commented on services/sessionservice/session.go
> +		panic("The logout function SHOULD only be called when a user is authenticated")
not sure we want to panic in this case

2022-12-19 10:32 UTC, Zorin95670 commented on http_support_test.go
> +func (t *TestContext) iSigninAsWithPassword(username, password string) error {
Remove this as we discuss

2022-12-19 11:21 UTC, slashformotion commented on services/sessionservice/session.go
> +	fmt.Println(dur)
removed

2022-12-20 10:00 UTC, Zorin95670 commented on persistence/repository/CRUDRepositoryImpl.go
> +	clause := clause.OrderByColumn{Column: clause.Column{Name: sortOption.Column()}, Desc: sortOption.Desc()}
`clause := ` to `return clause.(...)`
Missing documentation

2022-12-20 13:03 UTC, Zorin95670 requested changes

2022-12-20 13:03 UTC, Zorin95670 commented on services/sessionservice/session.go
> +	dur := sessionService.sessionConfiguration.GetSessionDuration()
what is dur ?

2022-12-20 13:03 UTC, Zorin95670 commented on services/sessionservice/session.go
> +			// if the deletion of the session in the database was successfull,
successful

2022-12-20 13:07 UTC, Zorin95670 requested changes

2022-12-20 13:07 UTC, Zorin95670 commented on features/basic_auth.feature
> +
remove extra line

2022-12-20 13:07 UTC, Zorin95670 commented on features/basic_auth.feature
> +Feature: Login as superadmin using the basic authentification
this files is not lint and correctly indented

2022-12-20 13:07 UTC, Zorin95670 commented on features/basic_auth.feature
> +Scenario: Server should let us login/ with correct credentials
Should be a success on valid credentials

2022-12-20 13:07 UTC, Zorin95670 commented on features/basic_auth.feature
> +Scenario: Server return an error on invalid credentials
Should be an error on invalid credentials

2022-12-20 13:07 UTC, Zorin95670 commented on features/basic_auth.feature
> +Scenario: Server should let us login and logout
Should be a sucess if we logout after a successful login

2022-12-20 13:07 UTC, Zorin95670 commented on features/basic_auth.feature
> +Scenario: Server should return an error on logout without login first
Should be an error if we try to logout without login first

2022-12-22 08:51 UTC, Zorin95670 approved these changes

2022-12-22 08:51 UTC, merged